# Generated by Django 3.0.7 on 2020-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200621_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='tiktok_url',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='tiktok_id',
            field=models.SlugField(default='', max_length=256, verbose_name='TikTok id'),
            preserve_default=False,
        ),
    ]
