# Generated by Django 3.0.7 on 2020-06-27 23:03

from django.db import migrations, models

def create_zero_visits_object(apps, schema_editor):
    Visits = apps.get_model("api", "Visits")
    Visits.objects.create(visits=0)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200625_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.BigIntegerField(default=0, verbose_name='Number of visits')),
            ],
        ),
        migrations.RunPython(create_zero_visits_object),
    ]
