# Generated by Django 3.0.7 on 2020-06-15 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='deezer id')),
                ('itunes_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='apple id')),
                ('play_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='play id')),
                ('spotify_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='spotify id')),
                ('musicstory_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='musicstory id')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='deezer id')),
                ('itunes_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='apple id')),
                ('play_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='play id')),
                ('spotify_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='spotify id')),
                ('musicstory_id', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='musicstory id')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='song name')),
                ('image', models.URLField(blank=True, null=True, verbose_name='image url')),
                ('artists', models.ManyToManyField(to='api.Artist', verbose_name='artists')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_url', models.URLField(verbose_name='TikTok url')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Song', verbose_name='found song')),
            ],
        ),
    ]
