# Generated by Django 3.0.7 on 2020-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='deezer_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='deezer id'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='itunes_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='apple id'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='musicstory_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='musicstory id'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='play_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='play id'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='spotify id'),
        ),
        migrations.AlterField(
            model_name='song',
            name='deezer_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='deezer id'),
        ),
        migrations.AlterField(
            model_name='song',
            name='itunes_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='apple id'),
        ),
        migrations.AlterField(
            model_name='song',
            name='musicstory_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='musicstory id'),
        ),
        migrations.AlterField(
            model_name='song',
            name='play_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='play id'),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True, verbose_name='spotify id'),
        ),
    ]
