#!/bin/sh

set -o errexit
# set -o pipefail
set -o nounset

pyppeteer-install
python /app/manage.py migrate
python /app/manage.py collectstatic --noinput
# /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
#python /app/manage.py runserver 0.0.0.0:8000
gunicorn tiktune.wsgi:application --bind 0.0.0.0:9000 --chdir=/app
